### ISSUE TITLE
No module named 'agenda.metric_helper'

### ISSUE THREAD

**Issue by HITlilingzhi** [neural-dialogue-metrics/EmbeddingBased#1]
Hi,
I use your code to run embedding metrics and I have installed the latest version of agenda-1.0.2 with pip. I have met the error of "ModuleNotFoundError: No module named 'agenda.metric_helper'".

Could you tell me your version of agenda? May I do not use agenda? I just want to see the mean score of Average、Greedy and Extrema.

Thank you so much!

**Comment by cgsdfc** [comment]
hi, you may use the Eval project in this org. good luck!

**Comment by cgsdfc** [comment]
agenda is a silly helper lib that was replaced by Eval
